name: "Setup kicad"
description: "Install and setup kicad."
branding:
  icon: "download"
  color: "blue"

inputs:
  version:
    description: 'The kicad version in the following format: "x.y". For example: "9.0"'
    required: false
    default: "9.0"

runs:
  using: "composite"
  steps:
    - name: "Install KiCad on linux."
      run: ${{ github.action_path }}/install-kicad.sh "${{ inputs.version }}"
      shell: bash
